# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/paulus/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/CLion.app/Contents/bin/cmake/bin/cmake"

# The command to remove a file.
RM = "/Users/paulus/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/CLion.app/Contents/bin/cmake/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/paulus/Dropbox/Programs/C++/cpp11-tutorial_github

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/paulus/Dropbox/Programs/C++/cpp11-tutorial_github

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/paulus/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/CLion.app/Contents/bin/cmake/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/paulus/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/CLion.app/Contents/bin/cmake/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/paulus/Dropbox/Programs/C++/cpp11-tutorial_github/CMakeFiles /Users/paulus/Dropbox/Programs/C++/cpp11-tutorial_github/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/paulus/Dropbox/Programs/C++/cpp11-tutorial_github/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named debugging

# Build rule for target.
debugging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debugging
.PHONY : debugging

# fast build rule for target.
debugging/fast:
	$(MAKE) -f CMakeFiles/debugging.dir/build.make CMakeFiles/debugging.dir/build
.PHONY : debugging/fast

#=============================================================================
# Target rules for targets named builtin_types

# Build rule for target.
builtin_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 builtin_types
.PHONY : builtin_types

# fast build rule for target.
builtin_types/fast:
	$(MAKE) -f src/01_Objects/CMakeFiles/builtin_types.dir/build.make src/01_Objects/CMakeFiles/builtin_types.dir/build
.PHONY : builtin_types/fast

#=============================================================================
# Target rules for targets named pointers

# Build rule for target.
pointers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pointers
.PHONY : pointers

# fast build rule for target.
pointers/fast:
	$(MAKE) -f src/01_Objects/CMakeFiles/pointers.dir/build.make src/01_Objects/CMakeFiles/pointers.dir/build
.PHONY : pointers/fast

#=============================================================================
# Target rules for targets named references

# Build rule for target.
references: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 references
.PHONY : references

# fast build rule for target.
references/fast:
	$(MAKE) -f src/01_Objects/CMakeFiles/references.dir/build.make src/01_Objects/CMakeFiles/references.dir/build
.PHONY : references/fast

#=============================================================================
# Target rules for targets named arrays

# Build rule for target.
arrays: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arrays
.PHONY : arrays

# fast build rule for target.
arrays/fast:
	$(MAKE) -f src/01_Objects/CMakeFiles/arrays.dir/build.make src/01_Objects/CMakeFiles/arrays.dir/build
.PHONY : arrays/fast

#=============================================================================
# Target rules for targets named pointer_functions

# Build rule for target.
pointer_functions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pointer_functions
.PHONY : pointer_functions

# fast build rule for target.
pointer_functions/fast:
	$(MAKE) -f src/04_Functions/06_Pointer_Functions/CMakeFiles/pointer_functions.dir/build.make src/04_Functions/06_Pointer_Functions/CMakeFiles/pointer_functions.dir/build
.PHONY : pointer_functions/fast

#=============================================================================
# Target rules for targets named struct

# Build rule for target.
struct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 struct
.PHONY : struct

# fast build rule for target.
struct/fast:
	$(MAKE) -f src/05_Classes/01_Struct/CMakeFiles/struct.dir/build.make src/05_Classes/01_Struct/CMakeFiles/struct.dir/build
.PHONY : struct/fast

#=============================================================================
# Target rules for targets named class

# Build rule for target.
class: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 class
.PHONY : class

# fast build rule for target.
class/fast:
	$(MAKE) -f src/05_Classes/02_Class/CMakeFiles/class.dir/build.make src/05_Classes/02_Class/CMakeFiles/class.dir/build
.PHONY : class/fast

#=============================================================================
# Target rules for targets named file_io

# Build rule for target.
file_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_io
.PHONY : file_io

# fast build rule for target.
file_io/fast:
	$(MAKE) -f src/06_IO/CMakeFiles/file_io.dir/build.make src/06_IO/CMakeFiles/file_io.dir/build
.PHONY : file_io/fast

#=============================================================================
# Target rules for targets named output_buffer

# Build rule for target.
output_buffer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output_buffer
.PHONY : output_buffer

# fast build rule for target.
output_buffer/fast:
	$(MAKE) -f src/06_IO/CMakeFiles/output_buffer.dir/build.make src/06_IO/CMakeFiles/output_buffer.dir/build
.PHONY : output_buffer/fast

#=============================================================================
# Target rules for targets named iostate

# Build rule for target.
iostate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iostate
.PHONY : iostate

# fast build rule for target.
iostate/fast:
	$(MAKE) -f src/06_IO/CMakeFiles/iostate.dir/build.make src/06_IO/CMakeFiles/iostate.dir/build
.PHONY : iostate/fast

src/debugging.o: src/debugging.cpp.o

.PHONY : src/debugging.o

# target to build an object file
src/debugging.cpp.o:
	$(MAKE) -f CMakeFiles/debugging.dir/build.make CMakeFiles/debugging.dir/src/debugging.cpp.o
.PHONY : src/debugging.cpp.o

src/debugging.i: src/debugging.cpp.i

.PHONY : src/debugging.i

# target to preprocess a source file
src/debugging.cpp.i:
	$(MAKE) -f CMakeFiles/debugging.dir/build.make CMakeFiles/debugging.dir/src/debugging.cpp.i
.PHONY : src/debugging.cpp.i

src/debugging.s: src/debugging.cpp.s

.PHONY : src/debugging.s

# target to generate assembly for a file
src/debugging.cpp.s:
	$(MAKE) -f CMakeFiles/debugging.dir/build.make CMakeFiles/debugging.dir/src/debugging.cpp.s
.PHONY : src/debugging.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... debugging"
	@echo "... builtin_types"
	@echo "... pointers"
	@echo "... references"
	@echo "... arrays"
	@echo "... pointer_functions"
	@echo "... struct"
	@echo "... class"
	@echo "... file_io"
	@echo "... output_buffer"
	@echo "... iostate"
	@echo "... src/debugging.o"
	@echo "... src/debugging.i"
	@echo "... src/debugging.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

